[package]
name = "qwen3_tts"
version = "0.1.0"
edition = "2021"

[dependencies]
luminal = { path = "../.." }
luminal_nn = { path = "../../crates/luminal_nn" }
safetensors = "0.7.0"
half = "2.7.1"
hound = "3.5"

[[bin]]
name = "qwen3_tts_infer"
path = "src/main.rs"

[dev-dependencies]
candle-core = "0.9.1"
candle-nn = "0.9.1"
rand = "0.9.2"
